import { parsePurchaseOrders, upsertEntry, representativePatch, splitOrderNos, formatPurchaseOrders, getPurchaseOrders, allOrderNos } from "../../lib/purchase-orders";
const assert = (c: boolean, m: string) => { if (!c) { console.error("FAIL", m); process.exitCode = 1; } else console.log("ok", m); };
assert(parsePurchaseOrders(null).length === 0, "null → []");
assert(parsePurchaseOrders([{ order_no: " A ", quantity: "2" }, { bad: 1 }, { order_no: "" }]).length === 1, "정규화·불량 제거");
const e1 = upsertEntry([], { order_no: "A", pay_no: "P1", quantity: 1, source: "auto" });
const e2 = upsertEntry(e1, { order_no: "B", pay_no: "P2", quantity: 1, source: "auto" });
assert(e2.length === 2 && e2[0].order_no === "A", "append 순서");
const e3 = upsertEntry(e2, { order_no: "B", courier: "CJ", tracking_no: "111" });
assert(e3[1].tracking_no === "111" && e3[1].pay_no === "P2" && e3.length === 2, "병합 교체");
const rep = representativePatch(e3);
assert(rep.purchase_order_no === "A" && rep.tracking_no === "111" && rep.courier === "CJ", "대표 = 첫 주문번호 + 운송장 있는 첫 엔트리");
assert(representativePatch([]).purchase_order_no === null, "빈 목록 대표 null");
const legacy = getPurchaseOrders({ purchase_order_no: "L1", quantity: 3, purchase_detail_url: "u", tracking_no: "t" });
assert(legacy.length === 1 && legacy[0].quantity === 3 && legacy[0].detail_url === "u" && legacy[0].source === "manual", "구데이터 대표값 1건");
assert(getPurchaseOrders({ purchase_order_no: null, quantity: 1 }).length === 0, "주문번호 없음 → []");
assert(JSON.stringify(splitOrderNos("A, B / C | D\nA")) === JSON.stringify(["A","B","C","D"]), "주문번호 분리·중복제거");
assert(formatPurchaseOrders(e3) === "A(P1)×1 | B(P2)×1", "엑셀 표기");
assert(allOrderNos(e3).join() === "A,B", "allOrderNos");
console.log("DONE");
